### ISSUE TITLE
game crashes and wakes dont appear

### ISSUE THREAD

**Issue by CrystalClear51** [Goby56/wakes#11]
When i play in vanilla minecraft (with fabric api ofc) and join a world, I either instantly crash after the world loads, or crash after touching water, maybe its a performance issue cuz the game doesnt crash with the additive modpack, but even after that, the textures dont load when i move in water, its just normal water. i also play cracked minecraft if that has to do with anything

**Comment by nunes134** [comment]
That happened to me, then, i started using Iris Shaders and it stopped after that. But the Wakes didn't appear

**Comment by BLOKBUSTR** [comment]
I created a fresh 1.20.1 Fabric installation with only Fabric API and this mod. I made a new world and encountered the crash immediately when I or something else touched water. Here is a crash report which I hope will help:
https://gist.github.com/BLOKBUSTR/e3c57aa793eb7a528989d371b6bb9e62

**Comment by qxeii** [comment]
it is worth noting this issue only happens in the most recent release (the one which adds iris shader support)

**Comment by Goby56** [comment]
As stated by @qxeii, this issue is caused by Iris. The latest release (0.1.7) should fix this?
