### ISSUE TITLE
I added support for Valkyrien Skies

### ISSUE THREAD

**Issue by jamesgreen26** [Goby56/wakes#110]
This is not an issue report, I couldn't find a better way to get in touch. I made a compat mod for Wakes and Valkyrien Skies! Just wanted to let you know. I just submitted the mod on [modrinth](https://modrinth.com/mod/vs-wakes-compat). [Here's](https://github.com/jamesgreen26/vs2-wakes-compat) the source code. Thanks for making such a cool mod!
![2024-10-01_22 27 25-2](https://github.com/user-attachments/assets/7445fa02-3efe-4f79-ae69-bacd9b353c24)

**Comment by Goby56** [comment]
Let me know if you need any help migrating the compatibility mod to a newer version of the mod. 

Thank you for making this mod! I have actually given this a try a few months back but couldn't get it to work. Would you mind if I implemented this in the actual mod some time in the future?

**Comment by jamesgreen26** [comment]
Hey, my pleasure! I haven’t looked into updating it yet but I’ll reach out if I have trouble.

I think implementing this into wakes would be awesome! Maybe we can chat on discord? You can add me @g.mungus
