### ISSUE TITLE
Cauldron goes invisible when filled 

### ISSUE THREAD

**Issue by CaylinNeko** [Goby56/wakes#111]
**Describe the bug**
When filling the cauldron with water or lava the entire cauldron goes invisible

https://github.com/user-attachments/assets/a34fa037-a674-496b-b583-36f3a6badfad

When using the mod alone there is no issue, but when used with sodium (Sodium-fabric-0.5.11+mc1.20.1.jar is the one currently being used) this issue is replicated. I isolated the issue to this mod and sodium, as it is not replicable outside of the combination of the two mods. 

https://github.com/user-attachments/assets/612bff71-ef0a-4f3b-b344-4acba76ee104

**Hardware and OS**
This is happening for all users in the server, but my specs are
GPU                 Nvidia RTX 4090
Processor	AMD Ryzen 9 7950X 16-Core Processor               4.50 GHz
Installed RAM	128 GB (127 GB usable)
System type	64-bit operating system, x64-based processor
OS                    Windows 11 Pro

**Versions**
- Minecraft version 1.20.1
- Mod loader and version Curse Forge:  amendments-1.20-1.2.11-fabric.jar ; Sodium-fabric-0.5.11+mc1.20.1.jar ; ComplementaryReimagined_r5.2.2.zip 
- Fabric API (or quilt equivalent) version Fabric 0.16.5

**Comment by Goby56** [comment]
What fixed it?
