### ISSUE TITLE
Editing config file causes weird issues.

### ISSUE THREAD

**Issue by DillPickle66** [Goby56/wakes#118]
I'm working on a vanilla+ modpack and the only things I need to change in the config are "boat": "ONLY_SIMULATION" and 
"shaderLightPassthrough": 0.8. So, I removed the other lines in the config like I usually do when making mod packs, but it seems to break upon loading a world. It could be a formatting mistake on my part, but it looks correct to me.
Here's a screenshot of the config https://imgur.com/a/457NQac

{
	"effectSpawningRules": {
		"boat": "ONLY_SIMULATION"
	},
	"shaderLightPassthrough": 0.8
}

**Expected behavior**
It uses the two tweaked settings, and generates the rest of the config like normal. It also shouldn't crash when loading a world.

**To Reproduce**
Use the config file and load a world.

**Hardware and OS**
Windows 11
1050ti mobile
(same thing happened to my friend on an AMD system)

**Versions**
- 1.21.1
- Fabric 0.16.7
- Wakes 0.3.0
- Fabric API 0.108.0

**Comment by AMN-D** [comment]
Same Problem here,
i think instead of removing the entry for mobs and others we have to change the value passed to "FALSE" or something, if someone has a working config with YACL please share it here so that we can check the parameter.

**Comment by Goby56** [comment]
The accepted values for these entries should be any of the following: `SIMULATION_AND_PLANES`, `ONLY_SIMULATION`, `ONLY_PLANES`, `DISABLED`. I am in the middle of migrating the config handling from YACL to Midnightconfig and therefore the new config file will look a bit different just so that you are aware.
