### ISSUE TITLE
Ticking Entity Crash because of Dogs

### ISSUE THREAD

**Issue by GetNoob69** [Goby56/wakes#119]
**Describe the bug**
Everytime the tamed wolf (or dog) tries to teleport to me (im on singleplayer) the game crashes.

**Expected behavior**
The world loads just fine, the error occurs every single time a dog teleports.

**To Reproduce**
1. Tame a wolf
2. Move far away

**Screenshots**
Not available

**Hardware and OS**
Windows 11 and NVIDIA GTX1960.

**Versions**
- Minecraft version: 1.20.1
- Mod loader and version: Fabric 0.92.2 +1.20.1 
- Wakes version: 0.3.0 +1.20.1
- Fabric API (or quilt equivalent): version I do not know where to get this

**Additional information**
I use several mods, around 100 and the makeup shaders on low settings. The crash is marked as wakes error on the log. 

https://mclo.gs/rBimOR0
[CrashReportNeruina.log](https://github.com/user-attachments/files/17951065/CrashReportNeruina.log)

**Comment by Goby56** [comment]
Duplicate of #101
