### ISSUE TITLE
Visual bug when using with physics mod pro for oceans

### ISSUE THREAD

**Issue by Allternia** [Goby56/wakes#123]
**Describe the bug**
Wakes texture appears where the water is without physics while the boat is moving above and below the wakes textures

**Expected behavior**
I Knew this wasnt going to work but i was thinking it could've moved with the boat

**To Reproduce**
Turn ocean size to max on thunder and rain settings and use wakes  (ported with sinytra )

**Screenshots**
no screen shots taken atm

**Hardware and OS**
probably not a hardware issue

**Versions**
- Minecraft version 1.20.1
- Mod loader and version Neo'Forge
- Wakes version 2.4-3.0 
- Forgified fabric api

**Additional information**
The issue just might be this isnt coded in as a feature

**Comment by AMN-D** [comment]
The wakes texture is in 2d so it only shows on a 2d plane , i dont think this is a bug it is working as intented though itll be cool to see oceanphysics and wakes working together.

**Comment by Goby56** [comment]
As @AMN-D already mentioned, this isn't really a bug but just an incompatibility with Physics mod. I have no plans as of yet to make them compatible but if there is any updates in the future refer to issue #5.
