### ISSUE TITLE
[1.20.1 Quilt/Fabric] Wakes in 0.2.0 are all dark

### ISSUE THREAD

**Issue by Aninuscsalas** [Goby56/wakes#14]
All of the wake effects in the mod are black.

Qulit log : https://mclo.gs/hsEjMC7
Fabric log : https://mclo.gs/A4C5cwL

![2023-08-06_12 58 39](https://github.com/Goby56/wakes/assets/68734661/541e128e-2453-4eed-a62b-4a90d4c5cacc)

![2023-08-06_12 58 50](https://github.com/Goby56/wakes/assets/68734661/cc3bca33-db6e-4ce6-8340-f35ee6ca0f30)

**Comment by Goby56** [comment]
Is this only occuring on 0.2.0? Have you tried changing the wake style to either "Vibrant" or "Subtle"? ![wake style](https://github.com/Goby56/wakes/assets/60710855/df335b61-729b-4420-900c-09527fe1f638)
In issue #9 people had a similar problem but 0.1.8 seemed to fix it for them. For good measure could you send me your mods folder and config file for the mod as well?

**Comment by Aninuscsalas** [comment]
> Is this only occuring on 0.2.0? 

0.1.8 crashes on world load
https://mclo.gs/zQlWgqo

0.1.7 works fine
https://mclo.gs/Xu2OHjg

> Have you tried changing the wake style to either "Vibrant" or "Subtle"?

When changing it to "Vibrant" the effect completely disappears

> For good measure could you send me your mods folder and config file for the mod as well?

I only have Fabric API, ModMenu, YACL and Wakes 
I didn't change anything in the config

**Comment by ItsDev-python** [comment]
I get exactly the same issue including the fact that the trail completely disappears when turned into vibrant. Strange.

**Comment by TomyGamy** [comment]
are you on linux?

**Comment by XEnderB0yX** [comment]
> it happens on linux only, same modpack on windown, no problem

I have Windows and I have exactly the same problem

**Comment by ZedAmadeus** [comment]
I have the same problem–but I didn't always. I messed around with shaders a bit, and then something... broke. I have no idea why it happened but then when I went back to not using shaders, the wakes went black and disappeared when using vibrant. No idea how to unflick that switch, but hopefully that's... a little helpful for locating the problem

Anyway, really awesome mod. It's still quite usable when black if I just turn the opacity way down, have subtle ripples.

**Comment by Goby56** [comment]
Are you using fabulous graphics settings by any chance? It is very likely that this and issue #22 are related. I will be working on a fix in a couple of weeks.

**Comment by Lazerit** [comment]
I have the same problem on Mac with Prism Launcher and the latest version of fabric. Looking into the minecraft log, the only thing that seems relevant is this warning:
[13:13:19] [main/WARN]: Reference map 'wakes-refmap.json' for wakes.mixins.json could not be read. If this is a development environment you can ignore this message

0.1.8 has the same problem for me, 0.1.7 has the correct colors but the wakes aren't always showing up when moving through water without a boat

**Comment by Lazerit** [comment]
> Are you using fabulous graphics settings by any chance? It is very likely that this and issue #22 are related. I will be working on a fix in a couple of weeks.

Everything I described was with fancy graphic settings, turning fabulous on causes big chunks of water to not load at all, like in the screenshot you've sent in issue #22

Also, just wanted to thank you for making and maintaining this mod! It's really nice (when it works ;) )

**Comment by Goby56** [comment]
Alright, thank you for testing that out. Now we know these are separate issues.

**Comment by nostalgiaultra** [comment]
> Alright, thank you for testing that out. Now we know these are separate issues.

Well, when is the fix? I am not trying to sound pushy or anything, just curious.

**Comment by Goby56** [comment]
> Well, when is the fix? I am not trying to sound pushy or anything, just curious.

Yeah sorry for taking so long but I'm having trouble finding time working on the mod. On top of that it's very hard finding the cause of the issue because I've not been able to reproduce it myself. If anyone of you are using either MultiMC or Prism could you send me the instance where the bug is occuring?

**Comment by Goby56** [comment]
Oh and could you perhaps try and disabling water blending in the configs?

**Comment by Hex-4** [comment]
> Yeah sorry for taking so long but I'm having trouble finding time working on the mod. On top of that it's very hard finding the cause of the issue because I've not been able to reproduce it myself. If anyone of you are using either MultiMC or Prism could you send me the instance where the bug is occuring?

Here's a bare-bones [instance](https://drive.google.com/file/d/1ERFKNiKtAyIvJnmTkYFrEpMS8PLPMDTA/view?usp=sharing) where it occurs.

Disabling water blending didn't do anything for me on my primary instance with lots of other mods.

**Comment by Goby56** [comment]
Thank you for sending that! I'll take a look in a couple of weeks as I am unavailable right now.

**Comment by OskarBjorklund** [comment]
> Here's a bare-bones [instance](https://drive.google.com/file/d/1ERFKNiKtAyIvJnmTkYFrEpMS8PLPMDTA/view?usp=sharing) where it occurs.

Blud, your instace works fine on my computer💀

**Comment by nostalgiaultra** [comment]
> > Here's a bare-bones [instance](https://drive.google.com/file/d/1ERFKNiKtAyIvJnmTkYFrEpMS8PLPMDTA/view?usp=sharing) where it occurs.
> 
> Blud, your instace works fine on my computer💀

Well everyone else's, including mine, are broken. What did you do differently?

**Comment by Goby56** [comment]
If you experience dark wakes on your system, please install [this](https://github.com/Goby56/wakes/releases/tag/v0.2.1) version of the mod. It's purely a test build which means it doesn't fix anything. It will however help me figure out what is causing the dark textures. When installed, join a super flat water world and move around in the water. Note the values printed into chat and report them back here.

Thank you!

**Comment by nostalgiaultra** [comment]
so in a few weeks, once you get enough data from the test build we download, you will issue an update? also how do I "check for values" so I can report them here.

**Comment by Fernan181** [comment]
Hey, I just tried the mod on my Quilt 1.20.1 modpack with only wakes enabled (splashes disabled) and im getting the same message over and over again (it looks like this because of the Compact Chat mod, so i'm getting one message multiple times and the number between the parenthesys is just how many times i got it so ignore that).

![image](https://github.com/Goby56/wakes/assets/87091676/abc9cf2a-d7ae-40f0-9ddf-21cc0647c9fd)

Hope this can be useful to you.

**Comment by Hex-4** [comment]
(hello fellow KDE user!)
Yes, same number here on Linux (KDE neon). Fabric modloader with just the API and Mod Menu.
![image](https://github.com/Goby56/wakes/assets/121138331/b390a697-0803-44e3-b55a-a3952193fac3)
There is also that suspicious black area.

**Comment by Fernan181** [comment]
Thank you so much! Glad that you found the issue. Hopefully we can get this fixed soon. Dont burn yourself though and tysm!

(also hi Hex-4, lol; kde plasma ftw!!)

**Comment by Goby56** [comment]
The value printed in your chat is not out of the ordinary. There seems to be a different problem at hand. If you could take your time and download the latest [test build](https://github.com/Goby56/wakes/releases/tag/v0.2.1-t2) and follow the steps provided in the release I might be able to work something out.

**Comment by Goby56** [comment]
So `ENTITY_TRANSLUCENT_CULL` has color for you? When you say "almost" correct do you only refer to the values all being the same or do you see something that visually deviates from how it should look like? Because I think it looks pretty correct with that render type.

Thank you for testing! It now seems like the issue lies with the render type. Also good of you to provide OS and graphics card in your comment, that way I can get an understanding of why just certain people encounter the issue.

**Comment by Goby56** [comment]
Could you try changing the wake style to "vibrant" and see if the wakes look more like the gif?

**Comment by SaltSouls** [comment]
From what I can tell ENTITY_TRANSLUCENT_CULL is the one that works the most correctly, though I have noticed that when in third person and looking straight down, this causes the wakes to appear more transparent then when looking forward. The still look correct, but is subtly changes as the perspective becomes more top-down.

**Comment by Goby56** [comment]
Please try version [0.2.1](https://modrinth.com/mod/wakes/version/0.2.1). This should fix the dark wakes but you may have to disable fabulous graphics as it may collide with the fix I made.
