### ISSUE TITLE
[Feature Request]: Config Descriptions

### ISSUE THREAD

**Issue by Superkat32** [Goby56/wakes#15]
Wakes is an amazing mod. It works really well, and looks fantastic. However, I recently found myself playing with the config, and had no idea what option did what. YetAnotherConfigLib has an amazing way to easily add descriptions. They also aren't like normal Minecraft tooltips, which means you can have much longer descriptions without taking up all of the screenspace. On top of that, YACL also allows for image descriptions on-top of text descriptions! However, the downside to that is, depending on how many images you have, the file size will noticeably increase. So images must be used wisely.

I'm working on a PR to add text descriptions if you haven't already added them locally.

**Comment by Goby56** [comment]
Yeah descriptions would be really handy. I have not yet begun adding them so this PR would be really helpful. I'll take a look at it tomorrow.

Thanks for your contribution and glad you are enjoying the mod!

**Comment by Superkat32** [comment]
Thank you! I plan on trying to contribute to this mod more if I'm able to find anything. Keep up the great work!
