### ISSUE TITLE
Config menu: Mouse input changes Velocity required to produce a wake

### ISSUE THREAD

**Issue by 1rgend** [Goby56/wakes#18]
Whenever in the ModMenu config any mouse button is clicked while in the Wake behaviour tab, the value in this setting gets multiplied by 10. Even when I click on Save Changes. A workaround is to switch on another tab (Wake appearance or Debug) and click Save Changes there

**Comment by Goby56** [comment]
This seems to be a bug with YACL and should be fixed in their latest 3.3.0 release. See if just updating YACL works, otherwise you'll have to wait until the next release of Wakes. (I know that it has been a while since the last update but I am really busy with other stuff atm)
