### ISSUE TITLE
Wakes make water disappear

### ISSUE THREAD

**Issue by Mabra51** [Goby56/wakes#19]
Wakes and splashes make the water on which they render disappear visually.

![2023-08-14_20 02 28](https://github.com/Goby56/wakes/assets/12016338/49596deb-a8a2-413a-bd0e-6837e998e81a)

Minecraft version is 1.20.1 with Quilt and mod version 0.2.0

**Comment by Goby56** [comment]
I can unfortunately not work on the mod in the coming months. Either try another version or debug by removing mods one by one from your mods folder.

**Comment by Goby56** [comment]
Do you have *Fabulous!* graphics settings turned on?

**Comment by xXMolgadoGamer01Xx** [comment]
I'm not the one who post this issue, but I had the same issue with the Fabulous! graphics on

**Comment by Goby56** [comment]
Yeah this is most likely the bug demonstrated in issue #22. I will close this issue. Please refer to #22 in the future.
