### ISSUE TITLE
Splashes made by oars are unrealistic

### ISSUE THREAD

**Issue by torzod** [Goby56/wakes#2]
The splashes boats' oars make in this mod are very unrealistic, good rowing will generally only create small whirls, rather than large turbulent patches seen in the mod, with potentially splashes on entering the water. Given, square oars are definitely not ideal, so maybe they would.

I realize this is a somewhat inane issue to raise, but it stood out to me immediately upon seeing the mod previews, having spent a good amount of time on the water myself.

**Comment by Goby56** [comment]
The wave pattern produced by the oars is not by any means a realistic simulation of how it would actually look like. This is neither the case for the actual wakes as those would produce many waves with different wavelengths (in the mod I'm only simulating one).

That said, there is an option to dial down the strength of the waves for both the oars and the wake that is produced.

Here I've changed it from 100 to 10. I personally like the larger patches but if you prefer these and if they are more realistic, go ahead and change the value. This can be done if you have YACL and ModMenu installed.
![paddle_strength](https://github.com/Goby56/wakes/assets/60710855/626697b6-1078-454a-b13c-b50a4d5f11b7)
