### ISSUE TITLE
Wierd behavior with "Fabulous!" graphic settings

### ISSUE THREAD

**Issue by oce412** [Goby56/wakes#22]
![2023-09-04_16 55 29](https://github.com/Goby56/wakes/assets/64910727/b0621429-e59b-4507-8dcc-eadbc5a057e6)
![2023-09-04_16 55 32](https://github.com/Goby56/wakes/assets/64910727/2b8aa91f-db0d-4555-8c18-1e88a86e7712)

**Comment by MaxenceDC** [comment]
Same issue here

**Comment by Goby56** [comment]
In your screenshots it look like the wake is tilted at an angle. Is that also related to your issue or is it just the fact that the water below disappears? I was able to reproduce the following:

![2023-09-16_14 34 11](https://github.com/Goby56/wakes/assets/60710855/b9219988-ed84-41a6-9e9e-c98877865047)

**Comment by oce412** [comment]
@Goby56 , yes, tilting is related to my issue. I can show it in discord stream if you want to see it

**Comment by DarianLStephens** [comment]
I just encountered the same issue.
I'd love to see it fixed, Fabulous solves a lot of gripes I have with the game's transparency rendering.

**Comment by Goby56** [comment]
I realise that this might be the biggest issue with the mod right now. I've been unable to work on the mod for the past months but in a week or so I think I could find time and try to resolve this bug.

**Comment by Goby56** [comment]
The [latest update](https://modrinth.com/mod/wakes/version/0.2.1) (0.2.1) should fix this. Do keep in mind that it might not look exactly the same as with fancy graphics and that the wake style has to be "Vibrant". Please reopen this issue if further related problems show up.
