### ISSUE TITLE
Water under wakes keep disappearing

### ISSUE THREAD

**Issue by Terrorstrike129** [Goby56/wakes#27]
I've tried using every debug feature I can think of, and no matter what the highlighted debug tiles always disappear in-game.
![image](https://github.com/Goby56/wakes/assets/138547132/0270920b-91a7-4576-8677-195f0488840b)

**Comment by Goby56** [comment]
Do you have fabulous graphics settings turned on?

**Comment by Terrorstrike129** [comment]
I think
________________________________

**Comment by Goby56** [comment]
Well try turning it off and see if the bug remains. If you can see the water with either fancy or fast graphics on this is most likely a duplicate of #22.
