### ISSUE TITLE
(1.19.2) Only sources uploaded

### ISSUE THREAD

**Issue by DarianLStephens** [Goby56/wakes#28]
The only file available on Modrinth for 1.19.2 is the sources, which obviously doesn't work in a normal release environment.

**Comment by Goby56** [comment]
My bad. That's clearly wrong. I can unfortunately not fix it for another week or so.

**Comment by Goby56** [comment]
Switched the jar to the correct one: https://modrinth.com/mod/wakes/version/7tVvcrxC
