### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kittenvr** [Goby56/wakes#29]
a few logs from me and my friends crashes that were caused by the mod

https://mclo.gs/ekIc3me

https://mclo.gs/6DsJdRP

https://mclo.gs/G7TiMTm

https://mclo.gs/adea9U0

**Comment by kittenvr** [comment]
Why close?

**Comment by Goby56** [comment]
Do you still experience the issue?

**Comment by kittenvr** [comment]
i dont know, did you fix it?

**Comment by Goby56** [comment]
I have not been able to reproduce is and as no one else has gotten it I closed it. If you, however, are still experiencing it I will take a deeper dive.
