### ISSUE TITLE
Weird behavior with "Fabulous!" grafix settings again

### ISSUE THREAD

**Issue by oce412** [Goby56/wakes#33]
So.. Now the water doesn't disappear but the wakes're still rendering at wrong angle

![2023-12-21_14 37 01](https://github.com/Goby56/wakes/assets/64910727/c4cc0911-5517-4651-8878-3210ba2d666d)
![2023-12-21_14 37 34](https://github.com/Goby56/wakes/assets/64910727/c546b17c-d29a-4552-a125-c2c4a01563a9)
![2023-12-21_14 37 50](https://github.com/Goby56/wakes/assets/64910727/7adadc97-f513-4faa-a892-7f9b7286aefb)
![2023-12-21_14 37 58](https://github.com/Goby56/wakes/assets/64910727/49af0ce0-6393-4cb1-963a-9a2c33f385af)
![2023-12-21_14 38 12](https://github.com/Goby56/wakes/assets/64910727/d821b7fd-ec04-4a98-a4b2-580960b4f37e)

**Comment by Goby56** [comment]
And this only occurs when using fabulous graphic settings?

**Comment by oce412** [comment]
Yes

**Comment by Goby56** [comment]
Any updates on this? Have any of the new versions fixed it?

**Comment by oce412** [comment]
Just tested last version of the mod on 1.20.1 and it's absolutely fine, no displacing or anything like before. Yet on my own instance i play most of the time with 0.3.0 i'm having very same troubles as before. I'd assume it's some kind of incompatibility issue, but testing every mod will take a wile.
So now i'm happy to say: Yes, yes it was fixed. Congrats on this and happy X-Mass!
