### ISSUE TITLE
Wakes get darker for some reason

### ISSUE THREAD

**Issue by NathanCD12** [Goby56/wakes#34]
Wakes get darker at yaw 90 and -90
![2023-12-21_18 53 17](https://github.com/Goby56/wakes/assets/132736601/312538e5-4339-4e6d-8334-990f2e521545)
![2023-12-21_18 53 06](https://github.com/Goby56/wakes/assets/132736601/d8971774-d58d-43dc-a4e6-b251280fb8ed)
and slightly get darker at yaw 180 and 0
![2023-12-21_18 54 35](https://github.com/Goby56/wakes/assets/132736601/d94edf0f-f0bd-4d8a-84af-77c46e6f79fc)
![2023-12-21_18 53 54](https://github.com/Goby56/wakes/assets/132736601/e7cdb2f2-03c1-40f1-8334-5ef14cf2f5ea)

**Comment by Goby56** [comment]
Please try [0.2.3](https://modrinth.com/mod/wakes/version/0.2.3)
