### ISSUE TITLE
glitch with Planes repeating

### ISSUE THREAD

**Issue by Zorklis** [Goby56/wakes#35]
https://github.com/Goby56/wakes/assets/85455465/57ac0322-8e4f-44eb-8866-8d49a43ed893

**Comment by makumaku1974** [comment]
was about to report it too... thought it was a feature for Waterfalls.

**Comment by Goby56** [comment]
No this definitely looks like a bug. @Zorklis in your video, do you know if there are any items stuck in that block which could be causing the splashes?

**Comment by brycerobertson** [comment]
I had the same bug earlier, and it remained when no items were stuck and still remained when a block was placed and removed in the water where the effects were playing

**Comment by makumaku1974** [comment]
> No this definitely looks like a bug. @Zorklis in your video, do you know if there are any items stuck in that block which could be causing the splashes?

This should be a feature.

**Comment by Goby56** [comment]
> This should be a feature.

Well if there's no items inside the block there's no reason for those wakes to be there and therefore this should be considered a bug.

**Comment by Zorklis** [comment]
https://github.com/Goby56/wakes/assets/85455465/81f44f7b-ed54-430b-bbfa-228dda55520a

Definitely a bug with planes. Also I don't see the option to turn them off anymore in the settings, or it's not as intuitive how to turn it off.
Resetting or changing options did not help. 

Seems they duplicate when a block is destroyed? Not consistent behavior that I can pinpoint to. 

![javaw_2JfgoBfVl9](https://github.com/Goby56/wakes/assets/85455465/ed214c8c-29c2-4a89-bf8c-31c435295124)
.. I changed these four it disappeared.

after changing item to only simulation, those wakes went away. so that's it.

Personally I don't see why planes would be on anything other than boats going fast

**Comment by Palmboom76** [comment]
![Screenshot 2024-01-28 192347](https://github.com/Goby56/wakes/assets/127950331/86121ecd-e0ce-4dfd-a99d-441152e552f8)
same
