### ISSUE TITLE
(1.19.2) Wakes Ignore Light

### ISSUE THREAD

**Issue by DarianLStephens** [Goby56/wakes#36]
![2023-12-31_05 53 13](https://github.com/Goby56/wakes/assets/15375876/f1c78c3a-d308-4980-be34-d0bd9ad383f5)
They also ignore blindness, being visible in the fog beyond sight.

If it helps or matters, I've got Sodium and other mods which could potentially affect it.

**Comment by Goby56** [comment]
[0.2.3](https://modrinth.com/mod/wakes/version/0.2.3+1.19.2) should fix this

**Comment by DarianLStephens** [comment]
I appreciate the fix, but I can't use it yet, unfortunately.
Create for 1.19.2 is still incompatible with the latest Fabric API, which introduced the new shader stuff you're using.
