### ISSUE TITLE
Splashes dont disable when toggled off [1.20.4]

### ISSUE THREAD

**Issue by brycerobertson** [Goby56/wakes#37]
Setting the Wake Spawning option in ModMenu to "Only Wakes" does not disable the splashes from the player or boats, only disabling splashes entirely disables them.

https://github.com/Goby56/wakes/assets/59671638/ef7d19c3-1b45-47fb-a79a-f3c2bccd4f4a

**Comment by Goby56** [comment]
Try [0.2.3](https://modrinth.com/mod/wakes/version/0.2.3)

**Comment by PabloDubalom** [comment]
> Try [0.2.3](https://modrinth.com/mod/wakes/version/0.2.3)

On 0.2.3 as well.

**Comment by brycerobertson** [comment]
Just updated to 0.2.3 and when setting all the options to "Only Simulation" the splashes seem to toggle off correctly now.
