### ISSUE TITLE
[BUG] Iris Shaders have glitchy Wakes 

### ISSUE THREAD

**Issue by Zorklis** [Goby56/wakes#4]
I'm on 1.20.1 MC and Fabric.
Using Iris shaders on produces wakes textures to be glitchy
[Complementary Reimagined r2.2.1](https://modrinth.com/shader/complementary-reimagined/version/r2.2.1)
![javaw_JsV2WUlAhG](https://github.com/Goby56/wakes/assets/85455465/64ef5ea1-7f7c-406c-991f-bd7b209d1baf)

[Complementary Shaders v4.7.2](https://modrinth.com/shader/complementary-shaders-v4/version/v4.7.2)
![javaw_Y0LlilwiBD](https://github.com/Goby56/wakes/assets/85455465/990f5a61-c62a-4b0e-a77a-81c5e0f576b4)

[Shrimple v0.9](https://modrinth.com/shader/shrimple/version/v0.9)
![javaw_pv6HEyjIQU](https://github.com/Goby56/wakes/assets/85455465/350def9b-c1eb-4b85-b032-dc9c1911cd65)

**Comment by rainysux** [comment]
Can second this as well for 1.20, was just going to submit this as well, but for me I can see it if I dont look too up, but if I look forward it looks perfectly fine
![2023-07-07_14 25 56](https://github.com/Goby56/wakes/assets/113203852/55d0707a-92c0-49df-af3d-b5d662349834)
![2023-07-07_14 26 00](https://github.com/Goby56/wakes/assets/113203852/b0bea1e7-c058-4cb9-9ab0-1a62b818c509)

**Comment by Goby56** [comment]
What version of the mod are you guys using. Is it 0.1.5 or an earlier version?

**Comment by Zorklis** [comment]
Iris version is the latest one (https://modrinth.com/mod/iris/version/1.6.4+1.20) and Wakes also the latest [since I just discovered it :)] (https://modrinth.com/mod/wakes/version/0.1.5)

**Comment by rainysux** [comment]
I am playing on the version before this recent new version. I tried the new one right now and it makes it look like the first picture he had shared,

**Comment by Taleuxss** [comment]
same

**Comment by Goby56** [comment]
I've managed to fix it for Shrimple but now it is completely invisible for Complementary.

![2023-07-08_10 24 54](https://github.com/Goby56/wakes/assets/60710855/ea00c8a7-ab9e-494a-9186-0efd6f268817)

Btw @rainysux what shaders are you using?

**Comment by rainysux** [comment]
its called overimagined shaders, I like it because its very light weight and it still gives me shaders similar to complementary

**Comment by rainysux** [comment]
[OverimaginedShaders_r1.2.1-1.0.zip](https://github.com/Goby56/wakes/files/11991444/OverimaginedShaders_r1.2.1-1.0.zip)

**Comment by Goby56** [comment]
Both Shrimple and the Complementary shaders now work with the latest version (0.1.6). You need to use Iris though, Optifine will probably don't work.
