### ISSUE TITLE
Wakes are rendered on top of everything in the latest version (0.2.3-Quilt 1.20.1)

### ISSUE THREAD

**Issue by NolanHewitt** [Goby56/wakes#46]
![huge_2024-01-14_00 38 23](https://github.com/Goby56/wakes/assets/52480898/077cacfd-c04b-4e53-81f2-890cb66c25c1)

**Comment by SaltSouls** [comment]
They are also visible through entities. It would seem that their render order is just set incorrectly. This may have to do with the update that allowed wakes to be visible from under the water on fabulous graphics.
![2024-01-20_09 16 06](https://github.com/Goby56/wakes/assets/36361103/f32a0e7d-d0af-44b2-a39c-2609596bb84b)

**Comment by Goby56** [comment]
I find this really strange as it does not occur for me. Not with blocks or entities. If I would have to guess I would say that this is an issue involving hardware as only some people have the problem. 

In order to figure this out, please provide what OS and graphics card you have.

**Comment by NolanHewitt** [comment]
I have two separate system and it occurs on both. One is a laptop 3060, the other is a desktop 7900xtx.

**Comment by SaltSouls** [comment]
> I have two separate system and it occurs on both. One is a laptop 3060, the other is a desktop 7900xtx.

Are they both running Linux by chance?

**Comment by SkightMeow** [comment]
I'm having the same issue in my modpack, 

Currently running:
Win 11
Nvidia
3060

**Comment by ErakAcheron** [comment]
I can also confirm this bug for 1.20.1 Fabric on Windows 10 with an Nvidia 3060 graphics card, I was also running the Nvidium mod (which has worked fine with wakes previously), alongside Sodium, Lithium, Iris and Starlight

**Comment by Goby56** [comment]
Does this only occur with Wakes 0.2.3 or is it present in earlier versions as well?

**Comment by Blobbon** [comment]
It only occurs on wakes 0.2.3 for me

**Comment by SaltSouls** [comment]
Yeah, only on the newest version for me as well.

**Comment by Billnotic** [comment]
I have this issue too.

**Comment by Treetrain1** [comment]
i also have this issue on 0.2.3
more interestingly it renders through water too
(there is water in a lush cave below)
![image](https://github.com/Goby56/wakes/assets/39657565/9af91cca-b6d3-4d6d-b670-a96992c6f129)

**Comment by HaipaDev** [comment]
Same issue 0.2.3, I suspected Nvidium for messing with how the shaders are rendered, not sure why everybody here is experiencing it as well

**Comment by CocoManiaDX** [comment]
Can confirm on Fabric 1.20.1, Windows 10 with a Radeon RX6600
Only on the 0.2.3 version.
0.2.2 doesn't have the problem.

**Comment by NolanHewitt** [comment]
I went back to 0.2.2 like people suggested and that fixes it for me

**Comment by Zouzs** [comment]
Same hapenning to me.

I tried it on my 1.20.1 modpack and then only with this mod. Newest version (0.1.4) had this problem, i downgraded to the previous one (0.1.3) and it got fixed.

Ryzen 5600g, Rx580, Windows 10.

**Comment by PolyframeX** [comment]
My specs:

Mod: 0.2.3
Minecraft: 1.20.1
Fabric: 0.15.7
OS: Windows 11.
Graphics: NVIDA GeForce RTX 3070 TI.

**Comment by Goby56** [comment]
In order to work out what the problem is I need someone who has encountered this problem to change the shader program in the mod's config screen. Try and change it from AUTO to something else like ENTITY_TRANSLUCENT_CULL or GENERAL. You could also play around with the fabulous graphic option and see if that makes any difference.

Thanks for your patience and cooperation! Lets solve this once and for all.

**Comment by PolyframeX** [comment]
I was using only Fancy graphic settings. I never use fabulous. I'll try to test out the potential solution when I can.

**Comment by Rhett008** [comment]
I have this problem, but only when using shaders. Turning off shaders, I don't experience the issue. I'm using Makeup Ultrafast on 1.20.1

OS: Windows 11
GPU: RTX 3060 (laptop)

Minecraft: 1.20.1
Wakes: 0.2.3
Sodium: 0.5.8
Iris: 1.6.17
MakeUp-UltraFast Shaders: 8.9d

Other mods, might be of interest -
Lithium: 0.11.2
Continuity: 3.0.0 beta.4
Indium: 1.0.30
LambDynamicLights: 2.3.2

**Comment by Goby56** [comment]
Does downgrading to Wakes 0.2.2 fix it for you @Rhett008 with MakeUp Ultrafast on?

**Comment by Goby56** [comment]
Please test out the [latest test build](https://github.com/Goby56/wakes/releases/tag/v0.2.4-t1) and read the instructions in the release notes. (You will have to enable a setting in the config menu)

**Comment by PolyframeX** [comment]
The issue seems to be fixed, however it seems to be fixed even the depth debug disabled, so I'm not sure whats going on there. Another thing is weird flickering seems to show up with certain items and things. As shown here: https://github.com/Goby56/wakes/assets/80133652/41c020e5-dc2e-475c-91f4-eaf2c28d199b

**Comment by Rhett008** [comment]
> Does downgrading to Wakes 0.2.2 fix it for you @Rhett008 with MakeUp Ultrafast on?

Downgrading fixes the see-through bug, but I get dark/black splash effects now when using my shaders. Also can't see wakes from underwater (obviously not in this version) which was nice


> Please test out the [latest test build](https://github.com/Goby56/wakes/releases/tag/v0.2.4-t1) and read the instructions in the release notes. (You will have to enable a setting in the config menu)

Yes this also fixes the see-through bug, but I still get dark/black splash effects when using the shaders. I now can't see underwater wakes when using shaders, despite having this ability in 0.2.3

**Comment by Polarjd** [comment]
Enabling depth test in the test build fixed the occlusion issue, but caused the effect to disappear at high camera angles. I am however using a dev build of bliss, and this only seems to happen with shaders and depth check on.
