### ISSUE TITLE
Crash on start of the game

### ISSUE THREAD

**Issue by benio1394** [Goby56/wakes#54]
**Describe the bug**
A game crash on start

**Expected behavior**

**To Reproduce**

**Screenshots**

**Hardware and OS**

**Versions**
- 1.20.4
- fabric 0.15.6
- 0.2.3
- 0.95.1

**Additional information**
https://pastebin.com/sQvWW0J2

**Comment by janilowski** [comment]
Duplicate of #50

**Comment by Goby56** [comment]
> Duplicate of #50

As @janilowski said.

This will be fixed in the next release. Unclear when this will be as I also want to include another fix to a more pressing issue in the same update.
