### ISSUE TITLE
[1.20.1] black splashes

### ISSUE THREAD

**Issue by glittermutt** [Goby56/wakes#55]
not really sure what's causing this, i'm not using any shaders. latest fabric version and newest version of wakes :'3
https://github.com/Goby56/wakes/assets/134949309/1363e7e5-1303-4ce8-bb37-75e240427fea

**Comment by CrawlingPlanet** [comment]
i have the same problem, just worse
![image](https://github.com/Goby56/wakes/assets/159733209/4d008ac7-22d5-4f2f-8df6-28bdbc333e20)
its completly black

**Comment by Benjamin27182** [comment]
me too 
![image](https://github.com/Goby56/wakes/assets/75861281/ad6d8417-ca4f-4151-8a01-13ffec9f7b85)

**Comment by Cozy-Cardboard-Box** [comment]
Been having the same problem, good to know I'm not the only one having this issue.

**Comment by Cozy-Cardboard-Box** [comment]
fixed it apparently you are supposed to put "auto" to "general" because auto shader breaks it
