### ISSUE TITLE
Mod menu doesn't work

### ISSUE THREAD

**Issue by SecretiXz** [Goby56/wakes#59]
- Minecraft version: 1.20.1
- Mod loader: fabric
- Wakes version: 0.2.3
- Fabric API version: 0.91.0+1.20.1

![image](https://github.com/Goby56/wakes/assets/101691532/fc821469-aa5a-465d-b9ef-1c358bc98453)

**Comment by Goby56** [comment]
Which version of YACL do you have?

**Comment by SecretiXz** [comment]
> Which version of YACL do you have?

3.1.1, since it works unstable with new versions

**Comment by BioTechproject27** [comment]
I have the same versions and it works for me? I use 
3.2.2+1.20-fabric of YACL tho
