### ISSUE TITLE
You can see the waves behind the blocks

### ISSUE THREAD

**Issue by OverCart345** [Goby56/wakes#61]
**Hardware and OS**
1050ti + windows. 

**Versions**
- Minecraft version 1.20.4
- Mod loader fabric and version 0.15.7 
- Wakes version 0.2.3
- Fabric API version 0.96.11

![2024-03-24_13 15 26](https://github.com/Goby56/wakes/assets/82957545/1115a4d4-f635-47ec-bbf8-bde73e512493)

**Comment by Goby56** [comment]
Duplicate of #46
