### ISSUE TITLE
Did bluds eat the wakes🙏🙏🙏🙏🙏

### ISSUE THREAD

**Issue by Epik0rangutan** [Goby56/wakes#62]
![image](https://github.com/Goby56/wakes/assets/163749224/478acd05-6712-4fdf-8ad1-1acfb812c0f5)

![image](https://github.com/Goby56/wakes/assets/163749224/59a14f06-2815-40a6-abb1-57d7ef0aaf68)

Where are my fucking wakes

**Comment by Treetrain1** [comment]
Is this a joke?

**Comment by Epik0rangutan** [comment]
> Is this a joke?

no, there are just no wakes when the pig is walking sometimes. Maybe it's because of the optifine cem animations incompatibility.

**Comment by Goby56** [comment]
Could you try enabling debug boxes in the mod's config?
