### ISSUE TITLE
customization (question)

### ISSUE THREAD

**Issue by SecretiXz** [Goby56/wakes#67]
![image](https://github.com/Goby56/wakes/assets/101691532/59838d6d-34b8-4834-a90c-9d310c20be6a)
is this possible to disable these waves in front of a player in mod config?

**Comment by Goby56** [comment]
Yes, turn off splash planes for the player in the config screen. You can also have it only be turned off when in first person.

**Comment by BioTechproject27** [comment]
It would be cool to have different opacity settings for different contexts? E.g. I like 80% opacity splash planes when sitting in a boat, but when swimming an opacity of 60% is nice. Maybe depending on how much screen space they take up?

Also, some wakes animations play when the game is paused, is that intended?

**Comment by BioTechproject27** [comment]
Also also, the planes seem to linger a bit too long when decelerating, e.g. in a boat and "clip" into it
