### ISSUE TITLE
Fix crash with 1.20.6 / 1.21

### ISSUE THREAD

**Issue by KennyDevT** [Goby56/wakes#74]
**Describe the bug**
When you start Minecraft 1.20.6 or 1.21 with the wakes mod it crashes due to a Satin API bug it seems.

**Expected behavior**
Minecraft To Run Normally with wakes.

**To Reproduce**
Use Minecraft 1.20.6 or 1.21 with wakes.

**Log**
[Log](https://mclo.gs/Z9nsVH3)
**Hardware and OS**
Tested on HP Victus Laptop with a i5 12500H and a RTX 3050 Laptop GPU.
Both Linux and Windows used both crash.

**Versions**
- Minecraft 1.20.6 or 1.21
- Fabric 0.15.11
- Wakes 0.2.4-test & 0.2.3
- Fabric API 0.98.0+1.20.6 or 0.100.3+1.21

**Additional information**
Satin API has been updated so hoping its an easy fix.

**Comment by Goby56** [comment]
This will unfortunately have to wait until June

**Comment by KennyDevT** [comment]
Any Updates?

**Comment by Goby56** [comment]
I will try to find time before the weekend.

**Comment by PixelTails** [comment]
Any updates?

**Comment by Goby56** [comment]
Should be fixed for 1.21 with [0.2.5](https://modrinth.com/mod/wakes/version/0.2.5+1.21)
