### ISSUE TITLE
Comapt with physics mod water

### ISSUE THREAD

**Issue by sargeow** [Goby56/wakes#76]
**Describe the bug**
wakes are stuck at normal water Y level using the pro version of the physics mod

**Expected behavior**
to follow the flow of the water

**To Reproduce**
download physics mod and wakes mod

**Screenshots**
no

**Versions**
1.20.1
quilt latest
latest 1.20.1
latest QFAPI

**Additional information**
yes

**Comment by Goby56** [comment]
Duplicate of #5
