### ISSUE TITLE
Crashes when opening mod settings

### ISSUE THREAD

**Issue by nmsltr** [Goby56/wakes#78]
**Describe the bug**
When opening the mod settings using the mod menu, the game crashes.

**Versions**
- 1.20.1
- fabric 0.15.10
- 0.2.4
- Fabric API 0.91.0

[crash-2024-06-12_15.44.36-client.txt](https://github.com/user-attachments/files/15801362/crash-2024-06-12_15.44.36-client.txt)

**Comment by xR4YM0ND** [comment]
Same here, also [crash with Ticking items](https://mclo.gs/SdTbxes)

**Comment by Goby56** [comment]
This probably has something to do with YACL. I will not look into this as I am switching to Midnightconfig in future versions.
