### ISSUE TITLE
1.19 compatibility?

### ISSUE THREAD

**Issue by bIankface** [Goby56/wakes#8]
I like the mod alot but with the modpack I have for version 1.19.3, it isn't compatible. In the future will you release the mod to be compatible for previous version or not at all?

**Comment by Goby56** [comment]
The mod is in a quite early state and I will therefore prioritize updating the mod to the latest version of Minecraft. That said, I might consider backporting major releases of the mod to versions such as 1.19.3.

**Comment by Goby56** [comment]
I backported the mod to 1.19.2. The reason for 1.19.2 and not 1.19.3 was because other mod dependencies which were only available on 1.19.2. Hope this isn't too much of an issue for you. If the mod doesn't work you could try [this fix](https://www.youtube.com/watch?v=GWB8loTTfw0&).
