### ISSUE TITLE
Memory leak caused by the mod

### ISSUE THREAD

**Issue by mineland-2048** [Goby56/wakes#89]
**Describe the bug**
Having the mod enabled and rowing on for a while eats memory up

**Expected behavior**
Memory should not get out of proportions

**To Reproduce**
Go in water and generate planes for a while

**Screenshots**

starting point (mod disabled via settings): 
![Screenshot_20240718_221504](https://github.com/user-attachments/assets/210e6968-c198-4532-a105-eb0bfe11c687)

around a minute of rowing with the mod enabled:
![Screenshot_20240718_221550](https://github.com/user-attachments/assets/00f6c1b2-efe8-4e98-a771-b543b75399cb)

rowing back after disabling the mod:
![Screenshot_20240718_221630](https://github.com/user-attachments/assets/1343791b-9506-42da-af6e-4bb129ace6c6)

**Hardware and OS**
CPU: Intel i7-6600U (4) @ 3.400GHz 
GPU: Intel Skylake GT2 [HD Graphics 520] 
RAM: 8gb (allocated 3gb max for the game)
OS: Fedora Linux 40 (KDE Plasma 6.1.2

**Versions**
- Minecraft 1.21
- Quilt Loader 0.26.4-beta.1
- Wakes 0.2.5+1.21
- Quilted Fabric API 11.0.0-alpha.3+0.100.7-1.21

**Additional information**
Disabling the mod via its debug setting stops the memory from increasing, but it doesnt clear what it has used already.

mod list used when testing:
[mod list 1.21.txt](https://github.com/user-attachments/files/16302510/mod.list.1.21.txt)

**Comment by Goby56** [comment]
0.3.0 should have resolved this. Please reopen the issue persists.

**Comment by mineland-2048** [comment]
Testing 0.3.0 on 1.21.1. It does look resolved so far after some minutes of rowing :+1:
