### ISSUE TITLE
Question: Which commit record for which branch for the 0.2.4+1.20.1 release?

### ISSUE THREAD

**Issue by iMoonDay** [Goby56/wakes#93]
I want the forge version of the mod, but you haven't released it yet, so I'd like to try porting it over myself, but I can't find which branch the latest version of 1.20.1 is, and there doesn't seem to be a branch that corresponds to 0.2.4+1.20.1. Can you point out which commit record for which branch is for 0.2.4+1.20.1? Or can you provide the source code for version 0.2.4+1.20.1?
If I successfully port, I'll push the code to you.
Much appreciated!

**Comment by Goby56** [comment]
It will probably just be the one before the 1.21 migration commit so: 3a5585cac4bc2b2b0e7d986fc3e7defef2dd0baa

**Comment by iMoonDay** [comment]
But I see that it has a release date of April 14, 2024, the commit for this is later than the release date and parts of the code don't line up with the released file. I'm guessing this [3b42a21](https://github.com/Goby56/wakes/commit/3b42a214a612419a6095a98b312c3fa98dcccfa1) is closer?

**Comment by Goby56** [comment]
Yes sorry, that seems like a better option. I forgot the commit I mentioned didn't support 1.20.1 and that you just wanted the most up to date code.

**Comment by iMoonDay** [comment]
Just found a problem: iris doesn't have a version for the forge side, does this affect how the code works?

**Comment by Goby56** [comment]
Yes, but it should not be harder than just removing the actual call to the Iris API. There should only be one such call and it is located in ``WakesClient.java`` under ``areShadersEnabled``.

**Comment by iMoonDay** [comment]
It seems that satin doesn't have a version for the forge side either, is there an alternative for this?

**Comment by Goby56** [comment]
That will be harder to fix. I'm using satin to create my own custom render type which is used when shaders are not enabled.
```java
if (WakesClient.CONFIG_INSTANCE.renderType == RenderType.AUTO) {
    if (WakesClient.areShadersEnabled()) {
        return ENTITY_TRANSLUCENT_CULL.program;
    } else {
        return CUSTOM.program;
    }
}
return WakesClient.CONFIG_INSTANCE.renderType.program;
```
You will either have to create such a render type yourself or settle with ``ENTITY_TRANSLUCENT_CULL`` which in my testing didn't look very good.

**Comment by iMoonDay** [comment]
In that case, unfortunately it looks like I won't be able to do the port for a while with my level of coding, but thanks for the answer.
